#!/bin/bash

# released under Creative Commons Attribution-ShareAlike 3.0
# http://creativecommons.org/licenses/by-sa/3.0/
# v1.4.0
# 1. 10. 2012
# dependencies: libcaca, mpc, mpd

#setting optional arguments
dflag=
rflag=

while getopts dr name
do
	case $name in
	d)	dflag=1;;
	r)	rflag=1;;
	?)	printf "Usage: Resize window: [-r]\nIncrease pixel density (use a smaller font)(only works in iTerm): [-d]\n"
		exit 2;;
	esac
done

#defining functions
function ascii {
	if [ -z "$dflag" ]; then
		faktor="1.87"
	else
		faktor="1.55"
	fi

	path=$(mpc -f %file% current)
	lib1=$(grep -a -m 1 music_directory ~/.mpdconf)
	lib2=$(echo ${lib1%\"*})
	librarypath=$(echo ${lib2#*\"})
	dirpath=$(dirname "$path")
	folderpath=$(echo $librarypath"/"$dirpath"/folder.jpg")
	height=$(tput lines)
	width=$(echo "$height*$faktor"|bc)
	if [ -f "$folderpath" ]; then
		art=$(img2txt -H $height -W $width --dither none "$folderpath")
		echo -e "$art""\c"
	else
		clear
		art=
	fi
}

#setting terminal window parameters
clear
printf "\033]2;ASCIICover\007"
ARGUMENTS="none"
read -s -t 1 -n 1 ARGUMENTS
terminal=$(echo $TERM_PROGRAM)
	#optional resizing
if [ -n "$rflag" ]; then
	if [[ "$terminal" == "iTerm.app" && ! -z "$(defaults read com.googlecode.iterm2|grep "\"Disable Window Resizing\" = 1;")" ]]; then
		osascript -e 'tell app "iterm" to set the bounds of the first window to {140, 120, 140+400-12, 120+400+6}'
	else
		printf "\033[4;388;380t"
	fi
fi
tput civis

# density stuff
if [ "$terminal" == "iTerm.app" && -n "$dflag" ]; then
	dim=$(osascript -e "tell application \"iterm\" to get the bounds of the first window" | sed "s/,/-/2" | sed "s/ //g")
	x1=${dim%%,*}
	y1=${dim#*,}
	y1=${y1%%-*}
	x2=${dim#*-}
	x2=${x2%%,*}
	y2=${dim##*,}
	let "dx=$x2-$x1-10"
	let "dy=$y2-$y1-20"
	osascript <<EOF
	tell application "iterm"
		activate
		tell application "System Events" to keystroke "-" using command down
		tell application "System Events" to keystroke "-" using command down
		tell application "System Events" to keystroke "-" using command down
		tell application "System Events" to keystroke "-" using command down
		tell application "System Events" to keystroke "-" using command down
		tell application "System Events" to keystroke "-" using command down
		set the bounds of the first window to {$x1, $y1, $x2, $y2}
	end tell
EOF
fi

#running the main loop
ascii
cols=$(tput cols)
while [ "$ARGUMENTS" != "q" ]; do
	if [[ "$(dirname "$(mpc -f %file% current)")" != "$dirpath" || "$(tput lines)" != "$height" || "$(tput cols)" != "$cols" || "$ARGUMENTS" == "r" ]]; then
		ascii
		cols=$(tput cols)
		ARGUMENTS="none"
	elif [ -z "$(mpc current)" ]; then
		: #do nothing
	else
		echo -e "$art""\c"
	fi
	sleep 1
	read -s -t 1 -n 1 ARGUMENTS
done

#resetting terminal window back to normal

# density stuff
if [ "$terminal" == "iTerm.app" && -n "$dflag" ]; then
	osascript <<EOF
	tell application "iterm"
		activate
		tell application "System Events" to keystroke "0" using command down
	end tell
EOF
	sleep 1
	printf "\033[4;$dy;$dx""t"
fi

tput cnorm
printf "\033]2;\007"
clear
exit